config/routes.rb
Rails.application.routes.draw do

  resources :sellings, only: [:index, :create]
  resources :products
  resources :coins, only: [:index, :edit, :update]

  root to: "sellings#index"
end

app/models/coin.rb
# Class with the coin inside the vending machine
# * value: the coin size in pence (1p 5p); for 1 Pound, insert 100p; for 2 Pound, insert 200p
# * quantity: the item quantity in stock
# * created_at: standard in RoR, is independent from the one that comes from the API
# * updated_at: standard in RoR, is independent from the one that comes from the API
# attr_accessor:
# * difference: the increasing/decreasing quantity

class Coin < ActiveRecord::Base
  include MathOperations

  attr_accessor :difference

  validates_presence_of   :value, :quantity
  validates               :value, numericality: { only_integer: true }, inclusion: { in: [1,2,5,10,20,50,100,200] }
  validates_uniqueness_of :value
  validates               :quantity,   numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates               :difference, numericality: { only_integer: true }, :if => "difference.present?"

  before_save :update_quantity

end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  # Show a table with the summary of the coins inside the Vending Machine
  def index
    @coins = Coin.all
    respond_to do |format|
      format.html
      format.json do
        render @coins.to_json
      end
    end
  end

  # Display a form to add coins (one type, how many like)
  def edit
    @coin = Coin.find(params[:id])
  end

  # Add the coins in database
  def update
    @coin = Coin.find(params[:id])
    if @coin.update(coin_params)
      # Respond to html with a redirect and json
      respond_to do |format|
        format.html do
          flash[:notice] = 'Quantity added'
          redirect_to coins_path
        end
        format.json do
          render json: @coin.to_json
        end
      end
    else
      respond_to do |format|
        format.html do
          flash.now[:error] = 'Error updating quantity'
          render :edit
        end
        format.json do
          render json: { errors: @coin.errors.full_messages }, status: 422
        end
      end
    end
  end

  private

  def coin_params
    params.require(:coin).permit(:difference)
  end
end

app/views/coins/edit.html.erb
<h1>Recharge <%=@coin.value_in_pound%> coin</h1>

<%=render('layouts/flashes') %>

<%= form_for @coin do |f| %>
  <div class="form-group">
    <%=f.label :difference%>
    <%=f.text_field :difference%>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Add' %>
    </div>
  </div>
<% end %>

<%=link_to 'Coins situation', coins_path%> |
<%=link_to 'Home', root_path%>

app/views/coins/index.html.erb
<h1>Coins situation</h1>

<table class="table table-hover">
  <thead>
  <tr>
    <td>ID</td>
    <td>Size</td>
    <td>Q.ty</td>
    <td>Actions</td>
  </tr>
  </thead>
  <tbody>
  <% @coins.each do |coin| %>
    <tr>
      <td>
        <%=coin.id%>
      </td>
      <td>
        <%=coin.value_in_pound%>
      </td>
      <td>
        <%=coin.quantity%>
      </td>
      <td>
        <%=link_to 'Add coins', edit_coin_path(coin) %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Home', root_path %>